import datetime
import json
import asyncio # Required for the test block

from .scraper import scrape_news, get_market_data
from .llm_service import generate_summary_from_llm

async def generate_report_data() -> dict:
    """
    Orchestrates the data fetching from scrapers, AI analysis from LLM service,
    and structures the final report according to PRD specifications.
    """
    print("Initiating report generation sequence...")

    # Step 1: Fetch data concurrently
    print("Fetching news and market data...")
    try:
        news_items, market_data_raw = await asyncio.gather(
            scrape_news(),
            get_market_data()
        )
        print(f"Successfully fetched {len(news_items)} news items.")
        print(f"Successfully fetched market data for: {', '.join(market_data_raw.keys())}")
    except Exception as e:
        print(f"Critical error during data scraping: {e}")
        # Return a minimal error structure or raise, depending on desired handling in main.py
        # For now, let's construct a report indicating failure at this stage.
        return {
            "report_date": datetime.date.today().strftime("%B %d, %Y"),
            "executive_summary": "Failed to generate report due to data scraping error.",
            "market_sentiment": {"sentiment": "Error", "reason": f"Scraping failed: {e}"},
            "key_indices": {},
            "top_stories": []
        }

    # Step 2: Get AI-generated summary and analysis
    print("Processing data with LLM service...")
    try:
        # llm_analysis is expected to contain: executive_summary, market_sentiment, top_stories
        llm_analysis = await generate_summary_from_llm(news_items, market_data_raw)
        print("LLM processing completed.")
    except Exception as e:
        print(f"Critical error during LLM processing: {e}")
        # Construct a report indicating failure at this stage, but include scraped data if available
        return {
            "report_date": datetime.date.today().strftime("%B %d, %Y"),
            "executive_summary": "Failed to generate report due to AI analysis error.",
            "market_sentiment": {"sentiment": "Error", "reason": f"LLM processing failed: {e}"},
            "key_indices": market_data_raw, # Return raw market data if LLM failed
            "top_stories": [ # Maybe include raw news titles if LLM failed to summarize
                {"title": news.get("title", "Raw news item"), "summary": "AI summary unavailable.", "url": news.get("url", "#"), "source": news.get("source", "Unknown")}
                for news in news_items[:3] # Show first 3 raw news items
            ]
        }

    # Step 3: Structure the final report according to PRD
    # "Report Structure" in PRD specifies these 4 main parts:
    # 1. One-liner summary (Executive Summary)
    # 2. Market Sentiment & Reason
    # 3. Key Indices (Name, Price, Change Amount, Change Percentage)
    # 4. Top 3 Stories (Title, LLM Summary, Original Link)

    final_report = {
        "report_date": datetime.date.today().strftime("%B %d, %Y"), # As per Header component spec

        "executive_summary": llm_analysis.get("executive_summary", "Executive summary not available."),

        "market_sentiment": {
            "sentiment": llm_analysis.get("market_sentiment", {}).get("sentiment", "Unknown"),
            "reason": llm_analysis.get("market_sentiment", {}).get("reason", "Reason not available.")
        },

        # key_indices should come directly from the scraper, as LLM is not supposed to modify it.
        # The scraper already formats it as: {"S&P 500": {"price": ..., "change": ..., "change_percent": ...}, ...}
        "key_indices": market_data_raw if market_data_raw else {
            "S&P 500": {"price": "N/A", "change": "N/A", "change_percent": "N/A"},
            "NASDAQ Composite": {"price": "N/A", "change": "N/A", "change_percent": "N/A"}
        },

        # top_stories are generated by the LLM.
        # Ensure it's a list and each story has the required fields.
        "top_stories": []
    }

    raw_llm_stories = llm_analysis.get("top_stories", [])
    if isinstance(raw_llm_stories, list):
        for story_data in raw_llm_stories[:3]: # Ensure only top 3 are taken
            final_report["top_stories"].append({
                "title": story_data.get("title", "Title not available"),
                "summary": story_data.get("summary", "Summary not available."),
                "url": story_data.get("url", "#"), # Default to "#" if URL is missing
                "source": story_data.get("source", "Source not available")
            })

    # If LLM provided fewer than 3 stories, this will just include what was provided.
    # If LLM provided more, it's truncated to 3.

    print("Report data structured successfully.")
    return final_report

if __name__ == '__main__':
    # More comprehensive test for report_generator.py
    async def main_test_report_generator():
        print("\n--- Testing Report Generator ---")

        # Mocking scraper and llm_service for isolated testing if needed,
        # but here we'll call the actual (mocked) dependencies.

        print("\nTest Case: Successful generation")
        report = await generate_report_data()
        print("\nFinal Report (Successful Case):")
        print(json.dumps(report, indent=2))

        # To test error conditions, you would ideally mock dependencies to throw errors.
        # For example, mock core.scraper.scrape_news to raise an Exception.
        # This is harder to do without a mocking library like unittest.mock or pytest's monkeypatch.

        # Simulating a scraper error by temporarily breaking a dependency (conceptually)
        # This is just for illustration; direct modification for testing isn't ideal.
        # _original_scrape_news = core.scraper.scrape_news
        # async def mock_scrape_news_error():
        #     raise ConnectionError("Simulated scraper connection error")
        # core.scraper.scrape_news = mock_scrape_news_error
        # print("\nTest Case: Scraper failure (conceptual - requires actual mocking)")
        # report_scraper_fail = await generate_report_data()
        # print("\nFinal Report (Scraper Failure Case):")
        # print(json.dumps(report_scraper_fail, indent=2))
        # core.scraper.scrape_news = _original_scrape_news # Restore

    asyncio.run(main_test_report_generator())
